## Occlusion Development

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
import sklearn
import tensorflow as tf
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)
    
from utils.utils import read_all_datasets

### Method for data shaping

In [ ]:
def shape_data(x_train, y_train, x_test, y_test):
    _x_train = x_train.copy()
    _y_train = y_train.copy()
    _x_test = x_test.copy()
    _y_test = y_test.copy()

    nb_classes = len(np.unique(np.concatenate((_y_train, _y_test), axis=0)))

    # transform the labels from integers to one hot vectors
    enc = sklearn.preprocessing.OneHotEncoder(categories='auto')
    enc.fit(np.concatenate((_y_train, _y_test), axis=0).reshape(-1, 1))
    _y_train = enc.transform(_y_train.reshape(-1, 1)).toarray()
    _y_test = enc.transform(_y_test.reshape(-1, 1)).toarray()

    # save orignal y because later we will use binary
    y_true = np.argmax(_y_test, axis=1)

    if len(x_train.shape) == 2:  # if univariate
        # add a dimension to make it multivariate with one dimension 
        x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
        x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))

    input_shape = x_train.shape[1:]

    return _x_train, _y_train, _x_test, _y_test, y_true, nb_classes, input_shape

### Load Data Set

In [11]:
## For Notebook
root_directory = 'C:/git/explic-ai-tsc'

## For PC
# root_directory = 'D:/git/explic-ai-tsc'

dataset_dict = read_all_datasets(root_directory, 'UCRArchive_2018')

curr_dataset = 'ECG5000'

x_train, y_train, x_test, y_test = dataset_dict[curr_dataset]

x_train, y_train, x_test, y_test, y_true, nb_classes, input_shape = shape_data(x_train, y_train, x_test, y_test)

### Load Pretrained Model

In [12]:
from classifiers import MLP

#### MLP
output_directory_model = 'C:/git/explic-ai-tsc/results/MLP/UCRArchive_2018_itr_0/ECG500/'
model = MLP(output_directory_model, input_shape, nb_classes, verbose=True, build=False)


### Dev Occlusion

In [13]:
from explanations import OcclusionSensitivityUTS

### Occlusion
explainer = OcclusionSensitivityUTS()

In [14]:
print(nb_classes)

5


In [10]:
patch_size = 4
num_samples = 10

np.random.randint(1, patch_size + 1, num_samples - 1)

array([2, 4, 3, 3, 2, 3, 3, 3, 4])

In [30]:
np.random.rand(20)

array([0.59326998, 0.12159727, 0.90696741, 0.55507409, 0.97757941,
       0.56842006, 0.82942125, 0.16534834, 0.43974652, 0.91736942,
       0.20090956, 0.27701349, 0.95575666, 0.74429007, 0.04957974,
       0.93257274, 0.96881302, 0.08247174, 0.20418264, 0.61797454])

In [23]:
[i for i in range(0, 20, 500)]

[0]

In [27]:
masks = [0, 1, 2, 3, 4]
[i for i in range(len(masks))]

[0, 1, 2, 3, 4]

In [28]:
ts = [0, 1, 2, 3]
m1 = [1, 2, 3, 4]

ts * m1

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
arr = [1, 1, 1, 1, 1, 1, 0, 0]

In [13]:
from scipy import signal

t = signal.resample(arr, 162, axis=0)
t

array([ 1.        ,  1.0256067 ,  1.0475792 ,  1.06595145,  1.08079578,
        1.0922209 ,  1.10036955,  1.1054157 ,  1.10756143,  1.10703359,
        1.10408009,  1.09896611,  1.09197012,  1.08337985,  1.07348815,
        1.06258899,  1.05097346,  1.03892592,  1.02672036,  1.01461695,
        1.0028589 ,  0.99166958,  0.98125007,  0.97177696,  0.96340073,
        0.95624434,  0.95040241,  0.94594077,  0.94289643,  0.94127803,
        0.94106665,  0.94221709,  0.94465943,  0.94830099,  0.95302865,
        0.95871134,  0.96520282,  0.97234468,  0.9799694 ,  0.98790357,
        0.99597114,  1.00399663,  1.01180832,  1.01924134,  1.02614056,
        1.03236335,  1.03778204,  1.04228617,  1.04578437,  1.04820593,
        1.04950207,  1.04964669,  1.04863689,  1.04649298,  1.04325815,
        1.03899772,  1.03379803,  1.02776493,  1.02102199,  1.01370832,
        1.00597617,  0.99798825,  0.98991485,  0.98193079,  0.97421229,
        0.96693373,  0.96026439,  0.95436526,  0.94938592,  0.94